---
- name: Enable static files in Galaxy
  ansible.builtin.lineinfile:
    path: "{{ subdomains_galaxy_config_file }}"
    line: '{{ subdomains_base_indentation }}static_enabled: true'

- name: Add static_*_by_host to gxconfig
  ansible.builtin.lineinfile:
    path: "{{ subdomains_galaxy_config_file }}"
    line: '{{ subdomains_base_indentation }}{{ static_key.key }}_by_host:'

- name: Set line in static_*_by_host variable for basedomain
  ansible.builtin.lineinfile:
    path: '{{ subdomains_galaxy_config_file }}'
    line: "{{ subdomains_base_indentation }}{{ subdomains_indentation }}'\
     {{ subdomains_instance_domain }}': '{{ subdomains_static_dir }}/{{ static_key.value }}'"
    insertafter: '{{ static_key.key }}_by_host:'
    state: present

- name: Set line in static_*_by_host variable for each subdomain
  ansible.builtin.lineinfile:
    path: '{{ subdomains_galaxy_config_file }}'
    line: "{{ subdomains_base_indentation }}{{ subdomains_indentation }}'{{ item }}.\
     {{ subdomains_instance_domain }}': '{{ subdomains_static_path }}/static-{{ item }}\
     /{{ static_key.value }}'"
    insertafter: '{{ static_key.key }}_by_host:'
    state: present
  loop: '{{ subdomains_subdomain_names }}'
