---
- name: Append themes_conf.yml to all files in galaxy/config/themes
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', subdomains_themes_conf_path) }}"
    path: "{{ subdomains_ansible_file_path}}/{{ subdomain.name }}/themes/{{ subdomain.name }}.yml"

- name: Add themes_config_file_by_host key to galaxy's config
  ansible.builtin.lineinfile:
    path: "{{ subdomains_galaxy_config_file }}"
    line: '{{ subdomains_base_indentation }}themes_config_file_by_host:'

- name: Add domain to themes_config_file_by_host in galaxy's config
  ansible.builtin.lineinfile:
    path: "{{ subdomains_galaxy_config_file }}"
    insertafter: 'themes_config_file_by_host:'
    line: "{{ subdomains_base_indentation }}{{ subdomains_indentation }}'\
     {{ subdomains_instance_domain }}': {{ subdomains_themes_conf_path | basename }}"

- name: Add entries for subdomains to themes_config_file_by_host in galaxy's config
  ansible.builtin.lineinfile:
    path: "{{ subdomains_galaxy_config_file }}"
    insertafter: 'themes_config_file_by_host:'
    line: "{{ subdomains_base_indentation }}{{ subdomains_indentation }}\
     '{{ subdomain.name }}.{{ subdomains_instance_domain }}': \
      {{ subdomain.name }}.yml"

- name: Copy themes files
  ansible.builtin.copy:
    src: "{{ subdomains_ansible_file_path}}/{{ subdomain.name }}/themes/{{ subdomain.name }}.yml"
    dest: "{{ galaxy_config_dir }}"
    mode: '0644'
