---
- name: Include Copy static files
  ansible.builtin.include_tasks: setup_static.yml
  loop: '{{ subdomains_subdomain_names }}'
  loop_control:
    loop_var: subdomain
  when: subdomains_serve_static

- name: Change Galaxy's config for static files (include add_static_config.yml)
  ansible.builtin.include_tasks: create_static_config.yml
  loop_control:
    loop_var: static_key
  loop: "{{ subdomains_static_keys | dict2items }}"
  when: subdomains_serve_static_config

- name: Change Galaxy's config for subdomain themes
  ansible.builtin.include_tasks: create_themes_config.yml
  loop: '{{ subdomains_themes_files }}'
  loop_control:
    loop_var: file
  when: subdomains_themes_per_host
